# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./../viewers
# Target is a subdirs project 

SUBDIRS += cameraControl \
           widgets 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
