# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./../system
# Target is a subdirs project 

SUBDIRS += gui \
           basics \
           streaming \
           properties \
           misc

CONFIG += release \
warn_on
TEMPLATE = subdirs
