# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./../images
# Target is a library:  

RESOURCES = geoX.qrc 
CONFIG += debug \
          warn_on \
          staticlib 
TEMPLATE = lib 
